@startuml
title GoF — Strategy
' ЛР6 — GoF UML
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam ArrowThickness 1
skinparam RoundCorner 12
skinparam defaultTextAlignment center
hide empty members
left to right direction

interface TransitionStrategy {
  +apply(order, db)
}

class ReviewTransitionStrategy
class CompleteTransitionStrategy
class CancelTransitionStrategy
class ChangeOrderStatusCommand

TransitionStrategy <|.. ReviewTransitionStrategy
TransitionStrategy <|.. CompleteTransitionStrategy
TransitionStrategy <|.. CancelTransitionStrategy

ChangeOrderStatusCommand --> TransitionStrategy : uses
@enduml
