from __future__ import annotations

from typing import Optional, Protocol

from app.models import LedgerEntry, Order, Product, UserPoints, Variant


class ProductRepository(Protocol):
    def add(self, product: Product) -> Product: ...
    def get(self, product_id: int) -> Optional[Product]: ...
    def list(self) -> list[Product]: ...
    def get_variants_by_skus(self, skus: list[str]) -> list[Variant]: ...
    def existing_skus(self, skus: list[str]) -> list[str]: ...
    def get_variant_for_update(self, sku: str) -> Optional[Variant]: ...


class OrderRepository(Protocol):
    def add(self, order: Order) -> Order: ...
    def get(self, order_id: int) -> Optional[Order]: ...
    def list(self) -> list[Order]: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class PointsRepository(Protocol):
    def get_for_update(self, user_id: str) -> Optional[UserPoints]: ...
    def ensure(self, user_id: str) -> UserPoints: ...


class LedgerRepository(Protocol):
    def add(self, entry: LedgerEntry) -> LedgerEntry: ...


class RepositoryFactory(Protocol):
    def products(self) -> ProductRepository: ...
    def orders(self) -> OrderRepository: ...
    def points(self) -> PointsRepository: ...
    def ledger(self) -> LedgerRepository: ...
